site_name: Pyfake
# site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/logo.png

  features:
    - navigation.tabs
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: light orange
      toggle:
        # icon: material/lightbulb
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: light orange
      toggle:
        # icon: material/lightbulb-outline
        icon: material/brightness-7
        name: Switch to light mode

# Navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/praneshmukhopadhyay/
    - icon: fontawesome/brands/github
      link: https://github.com/Mukhopadhyay

repo_url: https://github.com/Mukhopadhyay/pyfake
repo_name: Mukhopadhyay/pyfake

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
